# Generated by Django 4.2.2 on 2025-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
