# Generated by Django 4.2.2 on 2025-08-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="db.table",
            ),
        ),
    ]
