# Generated by Django 4.2.2 on 2025-08-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_booking_table"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["date"], name="date_index"),
        ),
        migrations.AlterModelTable(
            name="booking",
            table="bookings",
        ),
        migrations.AlterModelTable(
            name="table",
            table="tables",
        ),
    ]
